function varargout = VFUN(varargin)
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @VFUN_OpeningFcn, ...
                   'gui_OutputFcn',  @VFUN_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

function VFUN_OpeningFcn(hObject, eventdata, handles, varargin) %#ok<*INUSL>
handles.output = hObject;
guidata(hObject, handles);

str = IM2str([0.1,0.5,1,2,3,4]);
handles.port.Data={...
    'Class C1','vfunC1',str{1};...
    'Class C2','vfunC2',str{2};...
    'Class C3','vfunC3',str{3};...
    'Class C4','vfunC4',str{4};...
    'Class C5','vfunC5',str{5};...
    'Class C6','vfunC6',str{6}};

% uiwait(handles.figure1);

function varargout = VFUN_OutputFcn(hObject, eventdata, handles) 

varargout{1} = handles.output;
